import test from 'node:test'
import assert from 'node:assert/strict'
import { access, cp, mkdtemp, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'

const sourceRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))

const config = {
  projectName: 'Disposable Bootstrap Project',
  slug: 'disposable-bootstrap-project',
  purpose: 'Exercise Agent Project Starter bootstrap end to end',
  primaryUsers: 'Test users',
  repository: 'dn-lx/disposable-bootstrap-project',
  ownerTeam: 'dn-lx',
  branches: { integration: 'dev', production: 'prod' },
  architecture: {
    frontend: 'React Native / Expo',
    backend: 'Supabase Edge Functions',
    database: 'PostgreSQL',
    authentication: 'Supabase Auth',
    boundaries: 'Client calls authenticated APIs; privileged logic stays server-side',
  },
  commands: {
    install: 'npm ci',
    dev: 'npm run dev',
    test: 'node --test',
    build: 'npm run build',
    lint: 'npm run lint',
  },
  paths: {
    app: 'apps/mobile',
    tests: 'tests',
    database: 'supabase',
  },
  capabilities: {
    sourceControl: { status: 'Required', provider: 'GitHub', purpose: 'Source control and CI' },
    database: { status: 'Required', provider: 'Supabase', purpose: 'Auth, database and server-side functions' },
  },
}

function run(root, args) {
  return execFileSync(process.execPath, args, {
    cwd: root,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  })
}

test('full starter copy bootstraps and passes strict validation', async () => {
  const tempRoot = await mkdtemp(join(tmpdir(), 'agent-starter-e2e-'))
  const projectRoot = join(tempRoot, 'project')

  await cp(sourceRoot, projectRoot, {
    recursive: true,
    filter: source => !source.split(/[\\/]/).includes('.git'),
  })

  const configPath = join(projectRoot, 'bootstrap.e2e.json')
  await writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`, 'utf8')

  const bootstrapOutput = run(projectRoot, ['scripts/bootstrap-project.mjs', '--config', 'bootstrap.e2e.json'])
  assert.match(bootstrapOutput, /Updated 6 bootstrap targets/)

  const syncOutput = run(projectRoot, ['scripts/sync-claude-skills.mjs', '--write'])
  assert.match(syncOutput, /Claude skill adapters valid:/)

  // A new project must finish its identity and requirements before strict validation.
  assert.throws(() => run(projectRoot, ['scripts/validate-docs.mjs', '--strict-project']))

  await writeFile(join(projectRoot, 'README.md'),
    '# Disposable Bootstrap Project\n\nA test project created from Agent Project Starter.\n', 'utf8')
  await writeFile(join(projectRoot, 'docs/REQUIREMENTS.md'),
    '# Requirements\n\n## REQ-001 — Bootstrap\n\nThe generated project passes strict validation.\n', 'utf8')

  const docsOutput = run(projectRoot, ['scripts/validate-docs.mjs', '--strict-project'])
  assert.match(docsOutput, /Documentation valid:/)

  const stackOutput = run(projectRoot, ['scripts/validate-agent-stack.mjs'])
  assert.match(stackOutput, /Core agent stack valid:/)
  assert.match(stackOutput, /branch policy dev → prod/)

  const policy = JSON.parse(await readFile(join(projectRoot, '.agents/project-policy.json'), 'utf8'))
  assert.equal(policy.branches.integration, 'dev')
  assert.equal(policy.branches.production, 'prod')

  const memory = await readFile(join(projectRoot, 'docs/PROJECT-MEMORY.md'), 'utf8')
  assert.match(memory, /Disposable Bootstrap Project/)
  assert.match(memory, /Supabase Edge Functions/)

  const skill = await readFile(join(projectRoot, '.agents/skills/disposable-bootstrap-project/SKILL.md'), 'utf8')
  assert.match(skill, /name: disposable-bootstrap-project/)

  const adapter = await readFile(join(projectRoot, '.claude/skills/disposable-bootstrap-project/SKILL.md'), 'utf8')
  assert.match(adapter, /Generated by scripts\/sync-claude-skills\.mjs/)

  await assert.rejects(access(join(projectRoot, '.agents/skills/project-template/SKILL.md')))
  await assert.rejects(access(join(projectRoot, '.claude/skills/project-template/SKILL.md')))
})
