import { mkdir, readFile, writeFile, rm } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import process from 'node:process'

const CAPABILITIES = [
  ['sourceControl', 'Source control / PRs / CI', 'GitHub'],
  ['currentDocs', 'Current library/API docs', 'Context7 / official docs'],
  ['database', 'Database/auth/storage', 'Supabase / Firebase / vendor tool'],
  ['hosting', 'Hosting/deployments', 'Netlify / Vercel / Cloudflare'],
  ['browser', 'Browser/computer verification', 'Playwright / browser tooling'],
  ['codeRelationships', 'Code relationships', 'Graphify / code graph'],
  ['observability', 'Runtime observability', 'Sentry / vendor equivalent'],
  ['analytics', 'Product analytics/flags', 'PostHog / vendor equivalent'],
  ['payments', 'Payments', 'Stripe / equivalent'],
  ['email', 'Transactional email', 'Resend / equivalent'],
  ['documents', 'Documents/business files', 'Google Drive / SharePoint / Dropbox'],
  ['issues', 'Issue/project management', 'GitHub / Linear / Jira'],
]

const allowedStatuses = new Set(['Required', 'Optional', 'Not used'])

function required(value, name) {
  if (typeof value !== 'string' || !value.trim()) throw new Error(`Missing required bootstrap field: ${name}`)
  return value.trim()
}

function slugify(value) {
  return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

function normalizeConfig(input) {
  const projectName = required(input.projectName, 'projectName')
  const slug = input.slug ? slugify(input.slug) : slugify(projectName)
  if (!slug) throw new Error('Could not derive a project slug')
  const integration = required(input.branches?.integration ?? 'dev', 'branches.integration')
  const production = required(input.branches?.production ?? 'prod', 'branches.production')
  if (integration === production) throw new Error('integration and production branches must differ')
  if (integration !== 'dev' || production !== 'prod') {
    throw new Error('Bootstrap supports dev → prod only; adapting branch names requires the repository migration in docs/BRANCH-LIFECYCLE.md')
  }

  const capabilities = {}
  for (const [key] of CAPABILITIES) {
    const raw = input.capabilities?.[key] || {}
    const status = raw.status || (key === 'sourceControl' ? 'Required' : 'Not used')
    if (!allowedStatuses.has(status)) throw new Error(`Invalid capability status for ${key}: ${status}`)
    capabilities[key] = { status, provider: raw.provider || '', purpose: raw.purpose || '' }
  }

  return {
    projectName,
    slug,
    purpose: required(input.purpose, 'purpose'),
    primaryUsers: required(input.primaryUsers, 'primaryUsers'),
    repository: required(input.repository, 'repository'),
    ownerTeam: required(input.ownerTeam, 'ownerTeam'),
    branches: { integration, production },
    architecture: input.architecture || {},
    commands: input.commands || {},
    paths: input.paths || {},
    capabilities,
  }
}

function valueOr(value, fallback = 'Not configured') {
  return typeof value === 'string' && value.trim() ? value.trim() : fallback
}

function projectMemory(c) {
  const a = c.architecture
  const p = c.paths
  const cmd = c.commands
  return `# Project Memory\n\n> Generated by \`scripts/bootstrap-project.mjs\`. Keep this compact and durable; update it when architecture or operating contracts materially change.\n\n## Identity\n\n- **Project name:** ${c.projectName}\n- **Purpose:** ${c.purpose}\n- **Primary users:** ${c.primaryUsers}\n- **Repository:** ${c.repository}\n- **Owner/team:** ${c.ownerTeam}\n\n## Architecture\n\n- **Frontend/runtime:** ${valueOr(a.frontend, 'Not applicable')}\n- **Backend/runtime:** ${valueOr(a.backend, 'Not applicable')}\n- **Database/storage:** ${valueOr(a.database, 'Not applicable')}\n- **Hosting/deployment:** ${valueOr(a.hosting, 'Not configured')}\n- **Authentication:** ${valueOr(a.authentication, 'Not applicable')}\n- **Key architectural boundaries:** ${valueOr(a.boundaries, 'Define before implementation')}\n\n## Important paths\n\n| Area | Path |\n| --- | --- |\n| Main app | ${valueOr(p.app, 'Not configured')} |\n| Tests | ${valueOr(p.tests, 'Not configured')} |\n| Database/migrations | ${valueOr(p.database, 'Not applicable')} |\n| Public/static assets | ${valueOr(p.assets, 'Not applicable')} |\n| Infrastructure | ${valueOr(p.infrastructure, 'Not applicable')} |\n\n## Commands\n\n| Purpose | Command |\n| --- | --- |\n| Install | ${valueOr(cmd.install)} |\n| Development | ${valueOr(cmd.dev)} |\n| Test | ${valueOr(cmd.test)} |\n| Build | ${valueOr(cmd.build)} |\n| Lint/typecheck | ${valueOr(cmd.lint)} |\n| Browser/E2E | ${valueOr(cmd.e2e, 'Not used')} |\n| Performance | ${valueOr(cmd.performance, 'Not used')} |\n\n## Runtime environments\n\n- **Code promotion path:** \`${c.branches.integration} → ${c.branches.production}\`.\n- Branches are code-promotion lanes, not proof of runtime/data isolation.\n- Record concrete local, preview/staging and production runtime/data/auth targets before external writes.\n\n## Security boundaries\n\n- Authorization boundary: ${valueOr(a.authorization, 'Define before auth/data work')}\n- Secret storage: ${valueOr(a.secretStorage, 'Use host/repository/environment secret stores; never Git')}\n- Tenant/user isolation: ${valueOr(a.isolation, 'Not applicable / define if multi-user')}\n- Sensitive logging/data rules: ${valueOr(a.sensitiveData, 'Do not log secrets or sensitive personal data')}\n\n## External systems\n\nSee \`docs/MCP-SETUP.md\` for the generated capability profile. Credentials remain outside Git.\n\n## Durable decisions\n\n- \`docs/adr/0001-agent-independent-engineering.md\`\n\n## Context freshness\n\nSource, tests and accepted ADRs override stale memory.\n`
}

function mcpSetup(c) {
  const rows = CAPABILITIES.map(([key, label, typical]) => {
    const item = c.capabilities[key]
    return `| ${label} | ${item.status} | ${typical} | ${item.provider || (item.status === 'Not used' ? '—' : 'TBD')} | ${item.purpose || (item.status === 'Not used' ? 'Not used' : 'Define during integration')} |`
  }).join('\n')
  return `# MCP and Connector Setup\n\nExternal tool access is host-specific. This repository records capability requirements only; credentials and private tokens stay outside Git.\n\n## Project MCP profile\n\n| Capability | Status | Typical provider/tool | Project provider | Purpose |\n| --- | --- | --- | --- | --- |\n${rows}\n\n## Verification before use\n\nBefore relying on any connector: discover it in the current host, perform a harmless read, verify account/project/environment identity, verify permissions, then perform only the authorized write.\n\n## Security rules\n\n- Never commit API keys, OAuth tokens, passwords, certificates, service-role keys or private connector config.\n- Prefer least privilege and read-only investigation.\n- A development branch does not prove external data isolation.\n- Record material external writes in \`docs/CURRENT-HANDOFF.md\`.\n- For auth, data, payments, privileged functions or secrets, use the security-boundary-review skill.\n`
}

function projectSkill(c) {
  return `---\nname: ${c.slug}\ndescription: Project-specific durable guidance for ${c.projectName}.\n---\n\n# ${c.projectName}\n\n## Purpose\n${c.purpose}\n\n## Source of truth\n- Read \`AGENTS.md\` first.\n- Use \`docs/PROJECT-MEMORY.md\` for durable architecture, commands and boundaries.\n- Use \`docs/CURRENT-HANDOFF.md\` for unfinished task state.\n- Use \`docs/REQUIREMENTS.md\` for accepted requirements.\n\n## Branch flow\n- Integration: \`${c.branches.integration}\`\n- Production: \`${c.branches.production}\`\n- Ordinary work: temporary feature/fix/chore branch → \`${c.branches.integration}\`\n- Release: \`${c.branches.integration}\` → \`${c.branches.production}\` only after required checks and explicit approval.\n\n## Project rule\nDo not invent missing architecture, credentials, external-system identity or production state. Verify against current source/runtime/tool evidence.\n`
}

function policy(c) {
  return `${JSON.stringify({
    schema_version: 1,
    branches: { integration: c.branches.integration, production: c.branches.production, work_prefixes: ['feature/', 'fix/', 'chore/'] },
    release: { production_requires_explicit_approval: true, approval_label: 'production-approved', only_integration_may_target_production: true },
    continuity: { draft_pr_for_non_trivial_work: true, one_writer_per_task_branch: true, github_state_over_chat_memory: true },
  }, null, 2)}\n`
}

async function readOptional(path) {
  try {
    return await readFile(path, 'utf8')
  } catch (error) {
    if (error?.code === 'ENOENT') return null
    throw error
  }
}

function inspectSkillIndex(source) {
  if (!source) return { canonical: new Set(), projectSlug: null }
  const canonical = new Set()
  let projectSlug = null
  for (const line of source.split(/\r?\n/)) {
    const match = line.match(/^\|\s*(.*?)\s*\|\s*`([^`]+)`\s*\|$/)
    if (!match) continue
    const [, trigger, slug] = match
    if (trigger === 'Starter placeholder project knowledge') continue
    if (trigger === 'Project-specific durable guidance') {
      projectSlug = slug
      continue
    }
    canonical.add(slug)
  }
  return { canonical, projectSlug }
}

async function validateProjectSkillTarget(root, slug) {
  const index = await readOptional(join(root, '.agents/SKILL-INDEX.md'))
  const { canonical, projectSlug } = inspectSkillIndex(index)
  if (canonical.has(slug)) throw new Error(`Project slug collides with canonical skill: ${slug}`)
  if (projectSlug && projectSlug !== slug) {
    throw new Error(`Project slug is already ${projectSlug}; changing it to ${slug} requires an explicit migration`)
  }
}

async function write(root, path, content, dryRun, changed) {
  const target = join(root, path)
  changed.push(path)
  if (dryRun) return
  await mkdir(dirname(target), { recursive: true })
  await writeFile(target, content, 'utf8')
}

async function updateExisting(root, path, transform, dryRun, changed) {
  const target = join(root, path)
  const source = await readOptional(target)
  if (source === null) return
  const updated = transform(source)
  if (updated === source) return
  changed.push(path)
  if (!dryRun) await writeFile(target, updated, 'utf8')
}

export async function bootstrapProject(input, { root = process.cwd(), dryRun = false } = {}) {
  const c = normalizeConfig(input)
  await validateProjectSkillTarget(root, c.slug)
  const changed = []
  await write(root, '.agents/project-policy.json', policy(c), dryRun, changed)
  await write(root, 'docs/PROJECT-MEMORY.md', projectMemory(c), dryRun, changed)
  await write(root, 'docs/MCP-SETUP.md', mcpSetup(c), dryRun, changed)
  await write(root, `.agents/skills/${c.slug}/SKILL.md`, projectSkill(c), dryRun, changed)

  await updateExisting(
    root,
    '.agents/SKILL-INDEX.md',
    source => source.replace('| Starter placeholder project knowledge | `project-template` |', `| Project-specific durable guidance | \`${c.slug}\` |`),
    dryRun,
    changed,
  )

  await updateExisting(
    root,
    'docs/PROJECT-BOOTSTRAP-CHECKLIST.md',
    source => source.replace(
      '- [ ] Replace `.agents/skills/project-template/` with a real `.agents/skills/<project-name>/SKILL.md`; remove its obsolete generated `.claude/skills/project-template/` adapter and regenerate Claude adapters.',
      `- [x] Project-specific skill generated at \`.agents/skills/${c.slug}/SKILL.md\`; regenerate Claude adapters after bootstrap.`,
    ),
    dryRun,
    changed,
  )

  if (!dryRun && c.slug !== 'project-template') {
    await rm(join(root, '.agents/skills/project-template'), { recursive: true, force: true })
    await rm(join(root, '.claude/skills/project-template'), { recursive: true, force: true })
  }

  return { config: c, changed }
}

async function main() {
  const args = process.argv.slice(2)
  const getArg = name => {
    const index = args.indexOf(name)
    return index >= 0 ? args[index + 1] : undefined
  }
  const configPath = getArg('--config')
  const root = getArg('--root') || process.cwd()
  const dryRun = args.includes('--dry-run')
  if (!configPath) {
    console.error('Usage: node scripts/bootstrap-project.mjs --config <bootstrap.json> [--root <path>] [--dry-run]')
    process.exit(2)
  }
  const raw = JSON.parse(await readFile(configPath, 'utf8'))
  const result = await bootstrapProject(raw, { root, dryRun })
  console.log(`${dryRun ? 'Would update' : 'Updated'} ${result.changed.length} bootstrap targets for ${result.config.projectName}:`)
  for (const path of result.changed) console.log(`- ${path}`)
  if (!dryRun) console.log('Next: regenerate adapters and run strict project validation.')
}

if (import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  main().catch(error => { console.error(error.message); process.exit(1) })
}
