create index consents_data_source_idx on public.consents(data_source_id) where data_source_id is not null;
create index conversation_captures_data_source_idx on public.conversation_captures(data_source_id) where data_source_id is not null;
create index document_facts_document_idx on public.document_facts(document_id);
create index documents_data_source_idx on public.documents(data_source_id) where data_source_id is not null;
create index financial_accounts_data_source_idx on public.financial_accounts(data_source_id) where data_source_id is not null;
create index financial_transactions_data_source_idx on public.financial_transactions(data_source_id) where data_source_id is not null;
create index journal_entries_data_source_idx on public.journal_entries(data_source_id) where data_source_id is not null;
create index observations_data_source_idx on public.observations(data_source_id) where data_source_id is not null;
create index observations_raw_event_idx on public.observations(raw_event_id) where raw_event_id is not null;
create index practice_session_drills_session_idx on public.practice_session_drills(practice_session_id);
create index practice_session_drills_drill_idx on public.practice_session_drills(skill_drill_id);
create index practice_sessions_skill_idx on public.practice_sessions(skill_id);
create index relationship_reflections_interaction_idx on public.relationship_reflections(interaction_id) where interaction_id is not null;
create index skill_drills_subskill_idx on public.skill_drills(subskill_id);
create index skills_goal_idx on public.skills(goal_id) where goal_id is not null;
create index source_sync_runs_data_source_idx on public.source_sync_runs(data_source_id);
create index spiritual_sessions_practice_idx on public.spiritual_sessions(spiritual_practice_id) where spiritual_practice_id is not null;
create index subskills_parent_idx on public.subskills(parent_subskill_id) where parent_subskill_id is not null;
create index time_blocks_calendar_event_idx on public.time_blocks(source_calendar_event_id) where source_calendar_event_id is not null;
